// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNzsIqhlFDWc2SNtoJgVPFrNLUK9qmgk',
    appId: '1:589187819234:android:b29d9b9a60009f8fa660bb',
    messagingSenderId: '589187819234',
    projectId: 'sapi-d015a',
    storageBucket: 'sapi-d015a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXuhgK5KKEZkYYSq-35cwbS0YPQvA3ZE',
    appId: '1:589187819234:ios:126a698991237001a660bb',
    messagingSenderId: '589187819234',
    projectId: 'sapi-d015a',
    storageBucket: 'sapi-d015a.firebasestorage.app',
    iosBundleId: 'com.example.sapi',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPUQ7MQXAKT-voYG1I6HaVSHR50pRRcKY',
    appId: '1:589187819234:web:e47c4a6cde0c04cda660bb',
    messagingSenderId: '589187819234',
    projectId: 'sapi-d015a',
    authDomain: 'sapi-d015a.firebaseapp.com',
    storageBucket: 'sapi-d015a.firebasestorage.app',
  );
}
